# Generated by Django 5.0.7 on 2024-08-05 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0006_remove_profile_following_profile_followers_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='likes',
        ),
    ]
