# Generated by Django 5.1.1 on 2024-09-16 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cartilla', '0003_alter_pet_owner'),
        ('sistema', '0002_veterinian'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
