# Generated by Django 4.2.11 on 2024-03-31 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_subasta_category_subasta_image_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subasta',
            name='image_url',
            field=models.CharField(max_length=1024),
        ),
        migrations.AlterField(
            model_name='subasta',
            name='starting_bid',
            field=models.IntegerField(),
        ),
    ]
