# Generated by Django 4.2.11 on 2024-04-01 03:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_subasta_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='oferta',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='oferta',
            name='bid',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='oferta',
            name='subasta',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='auctions.subasta'),
        ),
        migrations.AlterField(
            model_name='oferta',
            name='text',
            field=models.CharField(default='none', max_length=64, null=True),
        ),
    ]
