# Generated by Django 4.2.11 on 2024-04-01 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_oferta_author_oferta_bid_oferta_subasta_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subasta',
            name='open',
            field=models.BooleanField(default=True),
        ),
    ]
