# Generated by Django 4.2.11 on 2024-04-02 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_comentario_author_comentario_subasta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subasta',
            name='category',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='subasta',
            name='image_url',
            field=models.CharField(blank=True, max_length=1024),
        ),
    ]
