# Generated by Django 5.1.1 on 2024-09-17 02:54

import cartilla.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='Pet name:')),
                ('kind', models.CharField(default='Sin especie', max_length=32, verbose_name='Kind')),
                ('photo', models.ImageField(blank=True, null=True, upload_to=cartilla.models.user_directory_path, verbose_name='Ingrese la foto de su mascota')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Milestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='Nombre del evento')),
                ('description', models.TextField(max_length=2048, verbose_name='Ingrese con detalle la descripccion del evento')),
                ('date', models.DateField(blank=True)),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='cartilla.pet')),
            ],
        ),
    ]
