# Generated by Django 5.1.1 on 2024-09-10 04:37

import cartilla.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Milestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='Nombre del evento')),
                ('description', models.TextField(max_length=2048, verbose_name='Ingrese con detalle la descripccion del evento')),
                ('date', models.DateField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='Pet name:')),
                ('photo', models.ImageField(blank=True, null=True, upload_to=cartilla.models.user_directory_path, verbose_name='Ingrese la foto de su mascota')),
            ],
        ),
    ]
