# Generated by Django 5.1.1 on 2024-09-10 04:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cartilla', '0001_initial'),
        ('sistema', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner', to='sistema.user'),
        ),
        migrations.AddField(
            model_name='milestone',
            name='pet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='cartilla.pet'),
        ),
    ]
