# Generated by Django 5.1.1 on 2024-09-17 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartilla', '0003_alter_pet_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='kind',
            field=models.CharField(default='Sin especie', max_length=32, verbose_name='Kind'),
        ),
    ]
